"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ScrollTrigger } from "@/motion/gsap";

type Board = number[]; // 9 cells, 0 = the gap

/**
 * Logic — a mechanical 8-puzzle that solves itself one move per scroll
 * increment. The move sequence is generated by scrambling from the solved
 * state (deterministically), then played in reverse: every state is valid
 * and the ending is always a solution.
 */
function buildStates(): Board[] {
  const solved: Board = [1, 2, 3, 4, 5, 6, 7, 8, 0];
  const picks = [1, 3, 0, 2, 1, 0, 3, 2, 0, 1, 2, 3, 1, 0];
  const states: Board[] = [solved];
  let board = solved.slice();
  let previousBlank = -1;

  for (const pick of picks) {
    const blank = board.indexOf(0);
    const row = Math.floor(blank / 3);
    const col = blank % 3;
    const candidates: number[] = [];
    if (row > 0) candidates.push(blank - 3);
    if (row < 2) candidates.push(blank + 3);
    if (col > 0) candidates.push(blank - 1);
    if (col < 2) candidates.push(blank + 1);
    const filtered = candidates.filter((c) => c !== previousBlank);
    const target = filtered[pick % filtered.length];
    const next = board.slice();
    next[blank] = next[target];
    next[target] = 0;
    previousBlank = blank;
    board = next;
    states.push(board);
  }
  return states.reverse();
}

export function RoomLogic() {
  const hostRef = useRef<HTMLDivElement>(null);
  const states = useMemo(buildStates, []);
  const [step, setStep] = useState(0);
  const solved = step === states.length - 1;

  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;
    const trigger = ScrollTrigger.create({
      trigger: host,
      start: "top 75%",
      end: "bottom 40%",
      onUpdate: (self) => {
        setStep(Math.min(states.length - 1, Math.floor(self.progress * states.length)));
      },
    });
    return () => trigger.kill();
  }, [states.length]);

  const board = states[step];
  const cell = 88;
  const gap = 8;

  return (
    <div ref={hostRef} className="flex flex-col items-center gap-5">
      <div
        className="relative rounded-lg border border-steel-soft bg-graphite p-3"
        style={{ width: cell * 3 + gap * 2 + 24, height: cell * 3 + gap * 2 + 24 }}
        aria-hidden
      >
        {[1, 2, 3, 4, 5, 6, 7, 8].map((tile) => {
          const index = board.indexOf(tile);
          const row = Math.floor(index / 3);
          const col = index % 3;
          return (
            <div
              key={tile}
              className={`absolute flex items-center justify-center rounded-sm border text-lg transition-all duration-300 ${
                solved
                  ? "border-ember/70 text-ember shadow-[0_0_18px_rgba(255,122,26,0.25)]"
                  : "border-steel text-mist"
              }`}
              style={{
                width: cell,
                height: cell,
                fontFamily: "var(--font-mono)",
                background: "var(--color-steel-soft)",
                transform: `translate(${col * (cell + gap) + 12}px, ${row * (cell + gap) + 12}px)`,
                transitionTimingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
              }}
            >
              {tile}
            </div>
          );
        })}
      </div>
      <span className="instrument text-[10px] tabular-nums">
        {solved ? "SOLVED" : `${String(states.length - 1 - step).padStart(2, "0")} →`}
      </span>
    </div>
  );
}
